/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.estetica_perros.vista;

import UsuarioExcepcion.UsuarioExcepcion;
import com.estetica_perros.controlador.ControladorUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author MARTINA
 */
public class JIFLoging_ extends javax.swing.JFrame {

    private ControladorUsuario controlUsuarios = new ControladorUsuario();
    public JIFLoging_() {
        initComponents();
        controlUsuarios = new ControladorUsuario();
        controlarEstadosMenus(false);
        txtCorreo.setText("lucaslopez@umanizales.edu.co");
        txtContrasenia.setText("12345");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jifLoging = new javax.swing.JInternalFrame();
        lblTipoUsuario = new java.awt.Label();
        chcAdministrador = new java.awt.Checkbox();
        chcUsuario = new java.awt.Checkbox();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuVerTabladePreciosSinDescuento = new javax.swing.JMenuItem();
        mnuVerTablasDeRegistro = new javax.swing.JMenuItem();
        mnuCotizar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifLoging.setTitle("INGRESO A LA TIENDA");
        jifLoging.setVisible(true);

        lblTipoUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoUsuario.setText("TIPO DE USUARIO");

        chcAdministrador.setLabel("ADMINISTRADOR");

        chcUsuario.setLabel("USUARIO");

        lblCorreo.setText("* CORREO:");

        lblContraseña.setText("* CONTRASEÑA");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLogingLayout = new javax.swing.GroupLayout(jifLoging.getContentPane());
        jifLoging.getContentPane().setLayout(jifLogingLayout);
        jifLogingLayout.setHorizontalGroup(
            jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLogingLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(lblContraseña))
                .addGap(18, 18, 18)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(txtContrasenia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLogingLayout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLogingLayout.createSequentialGroup()
                        .addComponent(chcAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(chcUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLogingLayout.createSequentialGroup()
                        .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLogingLayout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        jifLogingLayout.setVerticalGroup(
            jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLogingLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chcAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chcUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifLogingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        mnuInicio.setText("INICIO");

        mnuVerTabladePreciosSinDescuento.setText("VER TABLA DE PRECIOS");
        mnuVerTabladePreciosSinDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerTabladePreciosSinDescuentoActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuVerTabladePreciosSinDescuento);

        mnuVerTablasDeRegistro.setText("VER TABLAS DE REGISTRO");
        mnuVerTablasDeRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerTablasDeRegistroActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuVerTablasDeRegistro);

        mnuCotizar.setText("COTIZAR");
        mnuCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCotizarActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuCotizar);

        mnuSalir.setText("SALIR");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuSalir);

        jMenuBar1.add(mnuInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jifLoging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jifLoging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
 //TODO add your handling code here:

        if (txtCorreo.getText().equals("") || (txtContrasenia.getPassword().length == 0)
                || (chcAdministrador.getState() == false) && (chcUsuario.getState() == false)) {
            JOptionPane.showMessageDialog(rootPane, "Debe diligenciar todos los campos");
        } else {
            if (controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContrasenia.getText())) {
                jifLoging.hide();
                if (chcAdministrador.getState() == true) {
                    controlarEstadosMenus(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Los datos ingresados son errados");
            }
         if (controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContrasenia.getText())) {
                jifLoging.hide();
                if (chcUsuario.getState() == true) {
                    mnuVerTablasDeRegistro.setEnabled(false);
                    mnuVerTabladePreciosSinDescuento.setEnabled(true);
                    mnuVerTablasDeRegistro.setEnabled(false);
                    mnuCotizar.setEnabled(true);
                }} else {
                JOptionPane.showMessageDialog(rootPane, "Los datos ingresados son errados");
            }
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    public void controlarEstadosMenus(boolean estado){
        //mnuModificarContenido.setEnabled(estado);
        mnuVerTablasDeRegistro.setEnabled(estado);
        mnuVerTabladePreciosSinDescuento.setEnabled(estado);
        mnuVerTablasDeRegistro.setEnabled(estado);
        mnuCotizar.setEnabled(estado);
    }
    
    private void mnuVerTabladePreciosSinDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerTabladePreciosSinDescuentoActionPerformed
        // TODO add your handling code here:
        JIFTablaDePrecios abrir = new JIFTablaDePrecios();
        abrir.setVisible(true);
    }//GEN-LAST:event_mnuVerTabladePreciosSinDescuentoActionPerformed

    private void mnuVerTablasDeRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerTablasDeRegistroActionPerformed
        // TODO add your handling code here:
        JIFRegistroPerros abrirR = new JIFRegistroPerros();
        abrirR.setVisible(true);
        JIFRegistroUsuarios abrirU = new JIFRegistroUsuarios();
        abrirU.setVisible(true);
        
    }//GEN-LAST:event_mnuVerTablasDeRegistroActionPerformed

    private void mnuCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCotizarActionPerformed
        JIFPrecios abrir = new JIFPrecios();
        abrir.setVisible(true);
    }//GEN-LAST:event_mnuCotizarActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private java.awt.Checkbox chcAdministrador;
    private java.awt.Checkbox chcUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JInternalFrame jifLoging;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private java.awt.Label lblTipoUsuario;
    private javax.swing.JMenuItem mnuCotizar;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVerTabladePreciosSinDescuento;
    private javax.swing.JMenuItem mnuVerTablasDeRegistro;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
