/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.estetica_perros.vista;

import com.estetica_perros.modelo.Perro;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MARTINA
 */
public class JIFRegistroPerros extends javax.swing.JFrame {

    ArrayList<Perro> lista = new ArrayList<Perro>();
    public JIFRegistroPerros() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblNombre = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblCarnetVacunas = new javax.swing.JLabel();
        txtNombrePerro = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTamanio = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableRegistroPerros = new javax.swing.JTable();
        cbxCarnetVacunas = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("REGISTRO DE PERRO");
        jInternalFrame1.setVisible(true);

        lblNombre.setText("* NOMBRE DEL PERO:");

        lblPeso.setText("* PESO:");

        lblTamanio.setText("* TAMAÑO:");

        lblRaza.setText("RAZA:");

        lblCarnetVacunas.setText("* CARNET DE VACUNAS:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        JTableRegistroPerros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "PESO", "PESO", "TAMAÑO", "CARNET DE VACUNAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableRegistroPerros.getTableHeader().setResizingAllowed(false);
        JTableRegistroPerros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTableRegistroPerros);

        cbxCarnetVacunas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPeso)
                            .addComponent(lblNombre)
                            .addComponent(lblTamanio)
                            .addComponent(lblRaza)
                            .addComponent(lblCarnetVacunas))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaza)
                            .addComponent(txtTamanio)
                            .addComponent(txtPeso)
                            .addComponent(txtNombrePerro)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(cbxCarnetVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnGuardar)))))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombrePerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanio)
                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnetVacunas)
                    .addComponent(btnGuardar)
                    .addComponent(cbxCarnetVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        mnuInicio.setText("INICIO");

        mnuSalir.setText("SALIR");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuSalir);

        jMenuBar1.add(mnuInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public void escribirFichero() {
//        
//        FileWriter fichero = null;
//        
//        try{
//            fichero = new FileWriter("scr/AlmacenmientoPerros.txt");
//            PrintWriter prinW = new PrintWriter(fichero);
//            
//           // printW.println(lista);
//            
//        } catch (IOException ex){
//            System.out.println("Error al guardar el archivo" + ex.getMessage());
//        } finally{
//            try{
//                fichero.close();
//            } catch(IOException ex){
//                    System.out.println("Error al cerrar el archivo" + ex.getMessage());
//                }
//        }
//    }
    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if((txtNombrePerro.getText().equals("")) || (txtPeso.getText().equals("")) || 
                (txtRaza.getText().equals("")) || (txtTamanio.getText().equals(""))){
            JOptionPane.showMessageDialog(rootPane, "Debe de diligencia todos los campos");
        } else {
        Perro perro = new Perro(txtNombrePerro.getText(), txtPeso.getText() , txtRaza.getText() , txtTamanio.getText(), cbxCarnetVacunas.getSelectedItem().toString() );
        //public Perro(String nombre, double peso, String raza, String tamaño, boolean carnetVacunas)
        lista.add(perro);
        JOptionPane.showMessageDialog(rootPane, "GUARDADO CON ÉXITO");
        JOptionPane.showMessageDialog(rootPane, "El registro ha finalizado, tanto su usted como su perro han quedado registrados en el sistema");
        JIFLoging_ abrir = new JIFLoging_();
        abrir.setVisible(true);
        
        
        }
        
        
        mostrar();
        txtNombrePerro.setText("");
        txtPeso.setText("");
        txtRaza.setText("");
        txtTamanio.setText("");
        cbxCarnetVacunas.setSelectedItem("");
        
    }//GEN-LAST:event_btnGuardarActionPerformed

     public void mostrar(){
        String matriz [][] = new String [lista.size()][5];
        
            for(int i= 0; i< lista.size(); i++){
                matriz[i][0]= lista.get(i).getNombre();
                matriz[i][1]= lista.get(i).getPeso();
                matriz[i][2]= lista.get(i).getRaza();
                matriz[i][3]= lista.get(i).getTamaño();
                matriz[i][4]= lista.get(i).isCarnetVacunas();
                
            }
            
        JTableRegistroPerros.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "NOMBRE", "PESO", "PESO", "TAMAÑO", "CARNET DE VACUNAS"
            }
        ));
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableRegistroPerros;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCarnetVacunas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarnetVacunas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtNombrePerro;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtTamanio;
    // End of variables declaration//GEN-END:variables
}
