/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.estetica_perros.vista;

import com.estetica_perros.modelo.Perro;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARTINA
 */
public class JIFRegistroPerros extends javax.swing.JFrame {

    ArrayList<Perro> lista = new ArrayList<Perro>();
    DefaultTableModel model ;
    public JIFRegistroPerros() {
        initComponents();
        model =(DefaultTableModel)this.JTableRegistroPerros.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblNombre = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblCarnetVacunas = new javax.swing.JLabel();
        txtNombrePerro = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTamanio = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableRegistroPerros = new javax.swing.JTable();
        cbxCarnetVacunas = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnMostrarRegistro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("REGISTRO DE PERRO");
        jInternalFrame1.setVisible(true);

        lblNombre.setText("* NOMBRE DEL PERO:");

        lblPeso.setText("* PESO:");

        lblTamanio.setText("* TAMAÑO:");

        lblRaza.setText("RAZA:");

        lblCarnetVacunas.setText("* CARNET DE VACUNAS:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        JTableRegistroPerros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "PESO", "PESO", "TAMAÑO", "CARNET DE VACUNAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableRegistroPerros.getTableHeader().setResizingAllowed(false);
        JTableRegistroPerros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTableRegistroPerros);

        cbxCarnetVacunas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        btnAgregar.setText("AGREGAR A LA TABLA");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnMostrarRegistro.setText("MOSTRAR REGISTRO");
        btnMostrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPeso)
                            .addComponent(lblNombre)
                            .addComponent(lblTamanio)
                            .addComponent(lblRaza)
                            .addComponent(lblCarnetVacunas))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaza)
                            .addComponent(txtTamanio)
                            .addComponent(txtPeso)
                            .addComponent(txtNombrePerro)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(cbxCarnetVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar)
                                .addGap(45, 45, 45)))))
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarRegistro)
                .addGap(136, 136, 136))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombrePerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanio)
                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnetVacunas)
                    .addComponent(cbxCarnetVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarRegistro)
                    .addComponent(btnGuardar))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        mnuInicio.setText("INICIO");

        mnuSalir.setText("SALIR");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuInicio.add(mnuSalir);

        jMenuBar1.add(mnuInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
        FileWriter guardar = new FileWriter("src/datosPerros.txt");
        for(int i= 0; i < this.JTableRegistroPerros.getRowCount(); i++){   
//            guardar.write(lista.get(i).toString() + "\n");
            guardar.write(model.getValueAt(i, 0) + "\n");
            guardar.write(model.getValueAt(i, 1) + "\n");
            guardar.write(model.getValueAt(i, 2) + "\n");
            guardar.write(model.getValueAt(i, 3) + "\n");
            guardar.write(model.getValueAt(i, 4) + "\n");
            
        }
        guardar.close();
        JOptionPane.showMessageDialog(rootPane, "Datos guardados");
        JIFLoging_ abrir = new JIFLoging_();
        abrir.setVisible(true);
    }catch(Exception x){
        JOptionPane.showMessageDialog(rootPane, "Error al intentar guardar el archivo");
    
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
                if ((txtNombrePerro.getText().equals("")) || (txtPeso.getText().equals(""))
                || (txtRaza.getText().equals("")) || (txtTamanio.getText().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Debe de diligencia todos los campos");
        } else {
            model.addRow(new Object[]{txtNombrePerro.getText(), txtPeso.getText(),
                txtTamanio.getText(), txtRaza.getText()});
            txtNombrePerro.setText("");
            txtPeso.setText("");
            txtRaza.setText("");
            txtTamanio.setText("");
            cbxCarnetVacunas.setSelectedItem("");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRegistroActionPerformed
        String aux = "src/datosPerros.txt";
        String nombrePerro = txtNombrePerro.getText();
        String peso = txtPeso.getText();
        String tamanio = txtTamanio.getText();
        String raza = txtRaza.getText();
        String carnetVacunas = cbxCarnetVacunas.getSelectedItem().toString();

        Scanner linea = null;

        File doc = new File(aux);
        try {
            linea = new Scanner(doc);

            while (linea.hasNextLine()) {
                nombrePerro = linea.nextLine();
                peso = linea.nextLine();
                tamanio = linea.nextLine();
                raza = linea.nextLine();
                carnetVacunas = linea.nextLine();

                model.addRow(new Object[]{nombrePerro, peso, tamanio, raza, carnetVacunas});

            }
            
        } catch (Exception x) {
            JOptionPane.showMessageDialog(rootPane, "Error al intenta abrir el archivo");

        }
    }//GEN-LAST:event_btnMostrarRegistroActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableRegistroPerros;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarRegistro;
    private javax.swing.JComboBox<String> cbxCarnetVacunas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarnetVacunas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtNombrePerro;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtTamanio;
    // End of variables declaration//GEN-END:variables
}
